"""Deployment — Node 8.

Writes flat bundle to Databricks Workspace (/Workspace/Shared/),
creates app, waits for ACTIVE, deploys code, checks logs for success.
Returns URL only when app is confirmed running.

If deployment fails, captures error logs and sets deployment_error_logs
in state so the pipeline can route back to backend_dev for self-healing.
"""

import base64
import time

import httpx

from lakebase_accelerator.agent.state import PipelineState
from lakebase_accelerator.agent.tools import _get_repo
from lakebase_accelerator.settings import get_settings
from lakebase_accelerator.utils.logger import logger

WORKSPACE_BASE = "/Workspace/Shared/lakebase-accelerator-apps"
LOCAL_OUTPUT_DIR = "generated_apps"
MAX_DEPLOYMENT_RETRIES = 2


def deployment_node(state: PipelineState) -> dict:
    """Full deployment: write files → create app → deploy → check logs → return URL.

    On failure, captures error logs into state for self-healing retry.
    """
    logger.info("Node: deployment — starting", extra={"step": "deployment"})

    settings = get_settings()
    bundle_files = state.get("bundle_files", {})
    app_name = state["app_name"]
    schema_name = state["schema_name"]
    retry_count = state.get("deployment_retry_count", 0)

    if not bundle_files:
        return {"error": "No bundle files to deploy", "current_step": "deployment"}

    token = _get_token(settings)
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    # ─── Step 0: Write locally for inspection ────────────────────────
    _write_locally(app_name, bundle_files)

    # ─── Step 1: Clean workspace path (remove stale notebooks/files) ─
    workspace_path = f"{WORKSPACE_BASE}/{app_name}"
    logger.info(f"Cleaning workspace path: {workspace_path}", extra={"step": "deployment"})
    _clean_workspace(settings.databricks_host, token, workspace_path)

    # ─── Step 2: Write to Databricks Workspace (plain files, NOT notebooks)
    logger.info(f"Writing {len(bundle_files)} files to {workspace_path}", extra={"step": "deployment"})

    success_count = 0
    for file_path, content in bundle_files.items():
        full_path = f"{workspace_path}/{file_path}"
        if _write_file(settings.databricks_host, token, full_path, content):
            success_count += 1

    logger.info(f"Wrote {success_count}/{len(bundle_files)} files", extra={"step": "deployment"})

    if success_count == 0:
        return {"error": "Failed to write files to workspace", "current_step": "deployment"}

    # ─── Step 3: Create App ──────────────────────────────────────────
    logger.info(f"Creating app: {app_name}", extra={"step": "deployment"})

    # Check if app already exists
    check_resp = httpx.get(
        f"{settings.databricks_host}/api/2.0/apps/{app_name}",
        headers=headers,
        timeout=15.0,
    )

    if check_resp.status_code == 200:
        app_data = check_resp.json()
        logger.info(f"App already exists: {app_name}", extra={"step": "deployment"})
    else:
        create_resp = httpx.post(
            f"{settings.databricks_host}/api/2.0/apps",
            json={"name": app_name, "description": "Generated by Lakebase Accelerator"},
            headers=headers,
            timeout=30.0,
        )

        if create_resp.status_code not in (200, 201):
            return {"error": f"App creation failed: {create_resp.text[:200]}", "current_step": "deployment"}

        app_data = create_resp.json()

    app_url = app_data.get("url", "")
    sp_client_id = app_data.get("service_principal_client_id", "")

    logger.info(f"App ready: {app_name}, SP: {sp_client_id}", extra={"step": "deployment"})

    # ─── Step 4: Wait for ACTIVE ─────────────────────────────────────
    logger.info("Waiting for app compute to be ACTIVE...", extra={"step": "deployment"})
    if not _wait_for_active(settings.databricks_host, token, app_name, timeout=300):
        return {"error": "App did not reach ACTIVE state", "current_step": "deployment"}

    # ─── Step 5: Deploy code ─────────────────────────────────────────
    logger.info("Deploying code...", extra={"step": "deployment"})

    deploy_resp = httpx.post(
        f"{settings.databricks_host}/api/2.0/apps/{app_name}/deployments",
        json={"source_code_path": workspace_path},
        headers=headers,
        timeout=30.0,
    )

    if deploy_resp.status_code not in (200, 201):
        return {"error": f"Deployment failed: {deploy_resp.text[:200]}", "current_step": "deployment"}

    deployment_id = deploy_resp.json().get("deployment_id", "")
    logger.info(f"Deployment created: {deployment_id}", extra={"step": "deployment"})

    # ─── Step 6: Wait for deployment + check health ──────────────────
    logger.info("Waiting for deployment to complete...", extra={"step": "deployment"})
    deploy_status, deploy_message = _wait_for_deployment(
        settings.databricks_host, token, app_name, deployment_id, timeout=180
    )

    if deploy_status == "FAILED":
        # Fetch error logs for self-healing
        error_logs = _get_app_logs(settings.databricks_host, token, app_name, app_url)
        logger.error(f"Deployment failed. Logs: {error_logs[:500]}", extra={"step": "deployment"})

        # If we haven't exceeded retry limit, return error context for self-healing
        if retry_count < MAX_DEPLOYMENT_RETRIES:
            return {
                "deployment_error_logs": error_logs,
                "deployment_retry_count": retry_count + 1,
                "deployment_fix_context": _build_fix_context(error_logs, bundle_files),
                "current_step": "deployment",
                "error": "",  # Clear error so pipeline can retry
            }
        else:
            return {
                "error": f"App crashed after {MAX_DEPLOYMENT_RETRIES} retries. Logs: {error_logs[:300]}",
                "current_step": "deployment",
            }

    # ─── Step 7: Grant SP permissions ────────────────────────────────
    if sp_client_id:
        try:
            repo = _get_repo()
            repo.grant_schema_access(schema_name, sp_client_id)
            logger.info(f"Granted schema access to SP: {sp_client_id}", extra={"step": "deployment"})
        except Exception as e:
            logger.warning(f"Permission grant failed (non-fatal): {e}")

    # Get final URL
    if not app_url or app_url == "Unavailable":
        app_resp = httpx.get(f"{settings.databricks_host}/api/2.0/apps/{app_name}", headers=headers, timeout=15.0)
        if app_resp.status_code == 200:
            app_url = app_resp.json().get("url", f"{settings.databricks_host}/apps/{app_name}")

    logger.info(f"Deployment complete: {app_url}", extra={"step": "deployment"})

    return {
        "app_url": app_url,
        "service_principal_id": sp_client_id,
        "deployment_tested": True,
        "deployment_error_logs": "",
        "deployment_retry_count": retry_count,
        "current_step": "deployment",
        "completed_steps": state.get("completed_steps", []) + ["deployment"],
    }


# ═══════════════════════════════════════════════════════════════════════
# HELPERS
# ═══════════════════════════════════════════════════════════════════════


def _get_token(settings) -> str:
    response = httpx.post(
        f"{settings.databricks_host}/oidc/v1/token",
        data={"grant_type": "client_credentials", "scope": "all-apis"},
        auth=(settings.databricks_client_id, settings.databricks_client_secret),
        timeout=30.0,
    )
    return response.json()["access_token"]


def _clean_workspace(host: str, token: str, workspace_path: str) -> None:
    """Delete workspace directory recursively to remove stale notebooks/files."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    httpx.post(
        f"{host}/api/2.0/workspace/delete",
        json={"path": workspace_path, "recursive": True},
        headers=headers,
        timeout=15.0,
    )


def _write_file(host: str, token: str, path: str, content: str) -> bool:
    """Write a plain file to workspace.

    CRITICAL: Uses format="AUTO" WITHOUT language parameter.
    - format="AUTO" without language → creates a plain FILE
    - format="SOURCE" with language="PYTHON" → creates a NOTEBOOK (WRONG!)

    Databricks Apps need plain files, not notebooks, for uvicorn to import them.
    """
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    try:
        # Create parent directory
        parent = "/".join(path.rsplit("/", 1)[:-1])
        httpx.post(f"{host}/api/2.0/workspace/mkdirs", json={"path": parent}, headers=headers, timeout=15.0)

        # Encode content as base64
        encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")

        # Use format="AUTO" WITHOUT language — creates plain FILE, not notebook
        resp = httpx.post(
            f"{host}/api/2.0/workspace/import",
            json={"path": path, "content": encoded, "format": "AUTO", "overwrite": True},
            headers=headers,
            timeout=15.0,
        )

        if resp.status_code == 200:
            return True

        # If overwrite fails (existing notebook at path), delete first then retry
        httpx.post(
            f"{host}/api/2.0/workspace/delete",
            json={"path": path, "recursive": False},
            headers=headers,
            timeout=15.0,
        )
        resp = httpx.post(
            f"{host}/api/2.0/workspace/import",
            json={"path": path, "content": encoded, "format": "AUTO", "overwrite": True},
            headers=headers,
            timeout=15.0,
        )
        return resp.status_code == 200
    except Exception:
        return False


def _wait_for_active(host: str, token: str, app_name: str, timeout: int = 300) -> bool:
    headers = {"Authorization": f"Bearer {token}"}
    start = time.time()
    while time.time() - start < timeout:
        try:
            resp = httpx.get(f"{host}/api/2.0/apps/{app_name}", headers=headers, timeout=15.0)
            if resp.status_code == 200:
                state = resp.json().get("compute_status", {}).get("state", "")
                if state in ("RUNNING", "ACTIVE"):
                    return True
                if state in ("FAILED", "ERROR"):
                    return False
        except Exception:
            pass
        time.sleep(10)
    return False


def _wait_for_deployment(host: str, token: str, app_name: str, deployment_id: str, timeout: int = 180) -> tuple[str, str]:
    """Wait for deployment and return (status, message). Status: SUCCEEDED, FAILED, or TIMEOUT.

    Checks the specific deployment_id status, not the overall app status,
    to avoid detecting stale failures from previous deployments.
    """
    headers = {"Authorization": f"Bearer {token}"}
    start = time.time()

    # Give the deployment a few seconds to start before checking
    time.sleep(5)

    while time.time() - start < timeout:
        try:
            # Check the specific deployment status
            resp = httpx.get(
                f"{host}/api/2.0/apps/{app_name}/deployments/{deployment_id}",
                headers=headers,
                timeout=15.0,
            )
            if resp.status_code == 200:
                deploy_data = resp.json()
                deploy_state = deploy_data.get("status", {}).get("state", "")
                deploy_message = deploy_data.get("status", {}).get("message", "")

                if deploy_state == "SUCCEEDED":
                    return "SUCCEEDED", ""
                if deploy_state == "FAILED":
                    return "FAILED", deploy_message

            # Also check overall app status for RUNNING (means deployment succeeded)
            app_resp = httpx.get(f"{host}/api/2.0/apps/{app_name}", headers=headers, timeout=15.0)
            if app_resp.status_code == 200:
                app_data = app_resp.json()
                app_status = app_data.get("app_status", {}).get("state", "")
                # Only trust RUNNING status if the active deployment matches our deployment_id
                active_deploy = app_data.get("active_deployment", {})
                active_id = active_deploy.get("deployment_id", "")
                if app_status in ("RUNNING", "READY") and active_id == deployment_id:
                    return "SUCCEEDED", ""

        except Exception:
            pass
        time.sleep(10)
    return "TIMEOUT", "Deployment timed out"


def _get_app_logs(host: str, token: str, app_name: str, app_url: str) -> str:
    """Fetch app logs from the /logz/api/logs endpoint and Databricks API.

    The /logz endpoint on the app URL contains the actual error traceback.
    The Databricks API only gives generic "app crashed" messages.
    """
    headers = {"Authorization": f"Bearer {token}"}
    logs_parts = []

    # Try the app's /logz/api/logs endpoint (has the REAL error traceback)
    if app_url:
        try:
            logz_resp = httpx.get(
                f"{app_url.rstrip('/')}/logz/api/logs",
                headers=headers,
                timeout=15.0,
                follow_redirects=True,
            )
            if logz_resp.status_code == 200:
                logs_parts.append(f"App logs:\n{logz_resp.text[:3000]}")
        except Exception as e:
            logger.warning(f"Could not fetch /logz: {e}")

    # Also try fetching logs from the deployment-specific endpoint
    try:
        # Get the latest deployment details
        resp = httpx.get(f"{host}/api/2.0/apps/{app_name}", headers=headers, timeout=15.0)
        if resp.status_code == 200:
            data = resp.json()
            deploy_msg = data.get("active_deployment", {}).get("status", {}).get("message", "")
            app_msg = data.get("app_status", {}).get("message", "")
            app_url_from_api = data.get("url", "")

            if deploy_msg:
                logs_parts.append(f"Deploy message: {deploy_msg}")
            if app_msg:
                logs_parts.append(f"App status: {app_msg}")

            # If we didn't have app_url before, try again with the one from API
            if not app_url and app_url_from_api and not any("App logs:" in p for p in logs_parts):
                try:
                    logz_resp = httpx.get(
                        f"{app_url_from_api.rstrip('/')}/logz/api/logs",
                        headers=headers,
                        timeout=15.0,
                        follow_redirects=True,
                    )
                    if logz_resp.status_code == 200:
                        logs_parts.append(f"App logs:\n{logz_resp.text[:3000]}")
                except Exception:
                    pass
    except Exception:
        pass

    return "\n".join(logs_parts) if logs_parts else "Could not fetch logs"


def _build_fix_context(error_logs: str, bundle_files: dict[str, str]) -> str:
    """Build context string for the backend_dev node to fix deployment errors.

    Analyzes the error logs and provides targeted fix instructions.
    """
    context_parts = [
        "DEPLOYMENT FAILED — FIX REQUIRED",
        f"Error logs:\n{error_logs[:1500]}",
        "",
        "Current files in bundle:",
    ]

    # Include app.py and database.py content for context
    for key_file in ("app.py", "src/database.py", "src/routes/__init__.py", "requirements.txt"):
        if key_file in bundle_files:
            context_parts.append(f"\n--- {key_file} ---")
            context_parts.append(bundle_files[key_file][:500])

    # Analyze common error patterns and add specific fix instructions
    if "Could not import module" in error_logs:
        context_parts.append("\nFIX: The import in app.py is broken. Use 'from src.routes import router'")
    if "ResponseValidationError" in error_logs and "None" in error_logs:
        context_parts.append("\nFIX: Pydantic model has non-nullable field but DB returns NULL. Use Optional[str]")
    if "connection" in error_logs.lower() or "password" in error_logs.lower():
        context_parts.append("\nFIX: Database connection failed. Ensure OAuth token generation in src/database.py")
    if "ModuleNotFoundError" in error_logs:
        context_parts.append("\nFIX: Missing dependency in requirements.txt")

    return "\n".join(context_parts)


def _write_locally(app_name: str, bundle_files: dict[str, str]) -> None:
    """Write all files locally for inspection."""
    from pathlib import Path

    output_dir = Path(LOCAL_OUTPUT_DIR) / app_name
    for file_path, content in bundle_files.items():
        full_path = output_dir / file_path
        full_path.parent.mkdir(parents=True, exist_ok=True)
        full_path.write_text(content, encoding="utf-8")

    logger.info(f"Files written locally: ./{LOCAL_OUTPUT_DIR}/{app_name}/")
