"""Deploy a generated app to Databricks Workspace.

Usage:
    python scripts/deploy_app.py simple-notes-app-a5660f

This script:
1. Authenticates using SP credentials from .env
2. Cleans existing files/notebooks from workspace path
3. Writes all app files using Workspace Files Import API (plain files, NOT notebooks)
4. Creates the Databricks App (or reuses existing)
5. Triggers a deployment
6. Polls until deployment is READY or FAILED
7. Prints app URL and logs on failure
"""

import base64
import os
import sys
import time
from pathlib import Path

import httpx
from dotenv import load_dotenv

load_dotenv()

# ─── Configuration ───────────────────────────────────────────────────
DATABRICKS_HOST = os.getenv("DATABRICKS_HOST", "").rstrip("/")
DATABRICKS_CLIENT_ID = os.getenv("DATABRICKS_CLIENT_ID", "")
DATABRICKS_CLIENT_SECRET = os.getenv("DATABRICKS_CLIENT_SECRET", "")
WORKSPACE_BASE = "/Workspace/Shared/lakebase-accelerator-apps"
LOCAL_APPS_DIR = Path("generated_apps")

POLL_INTERVAL = 10  # seconds
MAX_WAIT_ACTIVE = 300  # seconds
MAX_WAIT_DEPLOY = 300  # seconds


def get_token() -> str:
    """Get workspace OAuth token using SP credentials."""
    print(f"  Authenticating with Databricks at {DATABRICKS_HOST}...")
    response = httpx.post(
        f"{DATABRICKS_HOST}/oidc/v1/token",
        data={"grant_type": "client_credentials", "scope": "all-apis"},
        auth=(DATABRICKS_CLIENT_ID, DATABRICKS_CLIENT_SECRET),
        timeout=30.0,
    )
    if response.status_code != 200:
        print(f"  ERROR: Auth failed: {response.status_code} — {response.text[:200]}")
        sys.exit(1)
    print("  ✓ Authenticated successfully")
    return response.json()["access_token"]


def delete_workspace_recursive(token: str, workspace_path: str) -> bool:
    """Delete a workspace path recursively (cleans up old notebooks/files)."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    resp = httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/workspace/delete",
        json={"path": workspace_path, "recursive": True},
        headers=headers,
        timeout=15.0,
    )
    return resp.status_code == 200


def write_file_to_workspace(token: str, workspace_path: str, content: bytes) -> bool:
    """Write a file using workspace/import with format AUTO (creates plain files, NOT notebooks).

    Key insight: Using format="AUTO" WITHOUT specifying language creates a plain FILE.
    Using format="SOURCE" with language="PYTHON" creates a NOTEBOOK.
    """
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    # Ensure parent directory exists
    parent = "/".join(workspace_path.rsplit("/", 1)[:-1])
    httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/workspace/mkdirs",
        json={"path": parent},
        headers=headers,
        timeout=15.0,
    )

    # Encode content as base64
    encoded = base64.b64encode(content).decode("utf-8")

    # Use format=AUTO without language — this creates a plain FILE, not a notebook
    resp = httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/workspace/import",
        json={"path": workspace_path, "content": encoded, "format": "AUTO", "overwrite": True},
        headers=headers,
        timeout=30.0,
    )

    if resp.status_code == 200:
        return True

    # If overwrite fails, delete first then retry
    httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/workspace/delete",
        json={"path": workspace_path, "recursive": False},
        headers=headers,
        timeout=15.0,
    )
    resp = httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/workspace/import",
        json={"path": workspace_path, "content": encoded, "format": "AUTO", "overwrite": True},
        headers=headers,
        timeout=30.0,
    )

    if resp.status_code == 200:
        return True

    print(f"    WARN: Failed to write {workspace_path}: {resp.status_code} — {resp.text[:150]}")
    return False


def create_app(token: str, app_name: str) -> dict:
    """Create a Databricks App (or return existing)."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    # Check if app already exists
    check_resp = httpx.get(
        f"{DATABRICKS_HOST}/api/2.0/apps/{app_name}",
        headers=headers,
        timeout=15.0,
    )
    if check_resp.status_code == 200:
        print(f"  ✓ App '{app_name}' already exists")
        return check_resp.json()

    # Create new app
    print(f"  Creating app '{app_name}'...")
    create_resp = httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/apps",
        json={"name": app_name, "description": "Generated by Lakebase Accelerator"},
        headers=headers,
        timeout=30.0,
    )

    if create_resp.status_code not in (200, 201):
        print(f"  ERROR: App creation failed: {create_resp.status_code} — {create_resp.text[:200]}")
        sys.exit(1)

    print(f"  ✓ App created")
    return create_resp.json()


def wait_for_active(token: str, app_name: str) -> bool:
    """Wait for app compute to be ACTIVE/RUNNING."""
    headers = {"Authorization": f"Bearer {token}"}
    print(f"  Waiting for app compute to be ACTIVE (max {MAX_WAIT_ACTIVE}s)...")

    start = time.time()
    while time.time() - start < MAX_WAIT_ACTIVE:
        resp = httpx.get(
            f"{DATABRICKS_HOST}/api/2.0/apps/{app_name}",
            headers=headers,
            timeout=15.0,
        )
        if resp.status_code == 200:
            data = resp.json()
            compute_state = data.get("compute_status", {}).get("state", "UNKNOWN")
            print(f"    Compute state: {compute_state}")
            if compute_state in ("RUNNING", "ACTIVE"):
                return True
            if compute_state in ("FAILED", "ERROR"):
                print(f"  ERROR: Compute failed: {data.get('compute_status', {})}")
                return False
        time.sleep(POLL_INTERVAL)

    print("  ERROR: Timeout waiting for compute")
    return False


def deploy_code(token: str, app_name: str, workspace_path: str) -> str:
    """Trigger a code deployment and return deployment_id."""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

    resp = httpx.post(
        f"{DATABRICKS_HOST}/api/2.0/apps/{app_name}/deployments",
        json={"source_code_path": workspace_path},
        headers=headers,
        timeout=30.0,
    )

    if resp.status_code not in (200, 201):
        print(f"  ERROR: Deployment trigger failed: {resp.status_code} — {resp.text[:200]}")
        sys.exit(1)

    deployment_id = resp.json().get("deployment_id", "unknown")
    print(f"  ✓ Deployment triggered: {deployment_id}")
    return deployment_id


def wait_for_deployment(token: str, app_name: str) -> tuple[str, str]:
    """Wait for deployment to complete. Returns (status, app_url)."""
    headers = {"Authorization": f"Bearer {token}"}
    print(f"  Waiting for deployment to complete (max {MAX_WAIT_DEPLOY}s)...")

    start = time.time()
    last_status = ""
    while time.time() - start < MAX_WAIT_DEPLOY:
        resp = httpx.get(
            f"{DATABRICKS_HOST}/api/2.0/apps/{app_name}",
            headers=headers,
            timeout=15.0,
        )
        if resp.status_code == 200:
            data = resp.json()
            app_status = data.get("app_status", {}).get("state", "UNKNOWN")
            app_url = data.get("url", "")

            # Also check active deployment status
            active_deployment = data.get("active_deployment", {})
            deploy_status = active_deployment.get("status", {}).get("state", "")
            deploy_message = active_deployment.get("status", {}).get("message", "")

            status_str = f"{app_status} | Deploy: {deploy_status}"
            if status_str != last_status:
                print(f"    {status_str}")
                last_status = status_str

            if app_status in ("RUNNING", "READY"):
                return "SUCCEEDED", app_url
            if "CRASH" in app_status.upper() or "FAIL" in app_status.upper() or "ERROR" in app_status.upper():
                print(f"    Deploy message: {deploy_message}")
                return "FAILED", app_url
            if deploy_status and "FAIL" in deploy_status.upper():
                print(f"    Deploy message: {deploy_message}")
                return "FAILED", app_url

        time.sleep(POLL_INTERVAL)

    return "TIMEOUT", ""


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/deploy_app.py <app_name>")
        print("Example: python scripts/deploy_app.py simple-notes-app-a5660f")
        sys.exit(1)

    app_name = sys.argv[1]
    app_dir = LOCAL_APPS_DIR / app_name

    if not app_dir.exists():
        print(f"ERROR: App directory not found: {app_dir}")
        sys.exit(1)

    print(f"\n{'='*60}")
    print(f"  DEPLOYING: {app_name}")
    print(f"  Source: {app_dir}")
    print(f"  Target: {WORKSPACE_BASE}/{app_name}")
    print(f"{'='*60}\n")

    # Step 1: Authenticate
    token = get_token()

    # Step 2: Clean existing workspace path (remove old notebooks)
    workspace_path = f"{WORKSPACE_BASE}/{app_name}"
    print(f"\n[Step 2] Cleaning existing workspace path...")
    if delete_workspace_recursive(token, workspace_path):
        print(f"  ✓ Cleaned: {workspace_path}")
    else:
        print(f"  (path didn't exist or already clean)")

    # Step 3: Write files using Workspace Files Import API (plain files)
    print(f"\n[Step 3] Writing files to workspace (as plain files, NOT notebooks)...")

    success_count = 0
    total_count = 0

    for file_path in app_dir.rglob("*"):
        if file_path.is_file():
            # Skip __pycache__ and hidden files
            rel_path = file_path.relative_to(app_dir)
            if "__pycache__" in str(rel_path) or str(rel_path).startswith("."):
                continue

            total_count += 1
            content = file_path.read_bytes()
            full_workspace_path = f"{workspace_path}/{rel_path.as_posix()}"

            if write_file_to_workspace(token, full_workspace_path, content):
                success_count += 1
                print(f"    ✓ {rel_path}")
            else:
                print(f"    ✗ {rel_path}")

    print(f"\n  Written: {success_count}/{total_count} files")

    if success_count == 0:
        print("  ERROR: No files written. Aborting.")
        sys.exit(1)

    # Step 4: Create app
    print(f"\n[Step 4] Creating/checking app...")
    app_data = create_app(token, app_name)
    sp_client_id = app_data.get("service_principal_client_id", "N/A")
    print(f"  Service Principal: {sp_client_id}")

    # Step 5: Wait for compute
    print(f"\n[Step 5] Waiting for compute...")
    if not wait_for_active(token, app_name):
        print("\n  FAILED: App compute did not become active.")
        sys.exit(1)

    # Step 6: Deploy code
    print(f"\n[Step 6] Deploying code...")
    deploy_code(token, app_name, workspace_path)

    # Step 7: Wait for deployment
    print(f"\n[Step 7] Waiting for deployment...")
    status, app_url = wait_for_deployment(token, app_name)

    if status == "SUCCEEDED":
        print(f"\n{'='*60}")
        print(f"  ✓ DEPLOYMENT SUCCESSFUL!")
        print(f"  URL: {app_url}")
        print(f"{'='*60}\n")
    else:
        print(f"\n{'='*60}")
        print(f"  ✗ DEPLOYMENT {status}")
        print(f"  URL: {app_url}")
        print(f"{'='*60}\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
