"""Centralized error code constants for the Lakebase Accelerator."""

# ─── Validation Errors ───────────────────────────────────────────────
VALIDATION_ERROR = "VALIDATION_ERROR"
PROMPT_EMPTY = "PROMPT_EMPTY"
PROMPT_TOO_LONG = "PROMPT_TOO_LONG"
INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
TOO_MANY_FILES = "TOO_MANY_FILES"

# ─── Pipeline Errors ─────────────────────────────────────────────────
PIPELINE_TIMEOUT = "PIPELINE_TIMEOUT"
PIPELINE_STEP_FAILED = "PIPELINE_STEP_FAILED"

# ─── LLM Errors ─────────────────────────────────────────────────────
LLM_ENDPOINT_NOT_READY = "LLM_ENDPOINT_NOT_READY"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_RESPONSE_INVALID = "LLM_RESPONSE_INVALID"
LLM_MAX_RETRIES_EXCEEDED = "LLM_MAX_RETRIES_EXCEEDED"

# ─── Schema Errors ───────────────────────────────────────────────────
SCHEMA_CREATION_FAILED = "SCHEMA_CREATION_FAILED"
SCHEMA_NAME_COLLISION = "SCHEMA_NAME_COLLISION"
SCHEMA_NOT_FOUND = "SCHEMA_NOT_FOUND"
CIRCULAR_FK_DEPENDENCY = "CIRCULAR_FK_DEPENDENCY"
TABLE_CREATION_FAILED = "TABLE_CREATION_FAILED"

# ─── Seed Data Errors ────────────────────────────────────────────────
SEED_DATA_GENERATION_FAILED = "SEED_DATA_GENERATION_FAILED"
SEED_DATA_CONSTRAINT_VIOLATION = "SEED_DATA_CONSTRAINT_VIOLATION"
SEED_DATA_INSERTION_FAILED = "SEED_DATA_INSERTION_FAILED"

# ─── App Generation Errors ───────────────────────────────────────────
FRONTEND_GENERATION_FAILED = "FRONTEND_GENERATION_FAILED"
BACKEND_GENERATION_FAILED = "BACKEND_GENERATION_FAILED"
DEPLOYMENT_CONFIG_FAILED = "DEPLOYMENT_CONFIG_FAILED"
MISSING_REQUIRED_FILES = "MISSING_REQUIRED_FILES"

# ─── Deployment Errors ───────────────────────────────────────────────
WORKSPACE_WRITE_FAILED = "WORKSPACE_WRITE_FAILED"
APP_CREATION_FAILED = "APP_CREATION_FAILED"
APP_DEPLOYMENT_FAILED = "APP_DEPLOYMENT_FAILED"
APP_DEPLOYMENT_TIMEOUT = "APP_DEPLOYMENT_TIMEOUT"

# ─── Permission Errors ───────────────────────────────────────────────
SP_DISCOVERY_FAILED = "SP_DISCOVERY_FAILED"
PERMISSION_GRANT_FAILED = "PERMISSION_GRANT_FAILED"

# ─── Database Errors ─────────────────────────────────────────────────
DB_CONNECTION_FAILED = "DB_CONNECTION_FAILED"
DB_QUERY_FAILED = "DB_QUERY_FAILED"

# ─── Project Errors ──────────────────────────────────────────────────
PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
